### ISSUE TITLE
fa icons not working

### ISSUE THREAD

**Issue by PabloRuizCuevas** [mintyfrankie/brilliant-CV#11]
**Describe the bug**
just seems that fa icons are not working for me, probably there is a super easy way to install them, just no idea how to do it also I don´t find any infomation on how to do it.

**To Reproduce**

**Expected behavior**
Icons work

**Screenshots**
![image](https://github.com/mintyfrankie/brilliant-CV/assets/48098178/41dd7775-2c3a-42a5-9d1e-f6f6edd9c980)

**Additional context**

**Comment by mintyfrankie** [comment]
Normally the fontawesome icons are imported automatically by the `fontAwesome` package, it's weird you cannot get it running.

Besides I see in your screenshot that the fonts were not correctly imported neither. 

Can you provide some more extra information on how you set it up, is there any error catched by typst-cli?

**Comment by PabloRuizCuevas** [comment]
yes, it may be because of the new version of typst, i think fontAwesome may not be working anymore, just tried to import it to a new project in the webapp with no luck, so the issue may not be in your package.

**Comment by mintyfrankie** [comment]
I've checked again, the `fontawesome` package does requires you to install the font locally in advance; yet I've already included it in the `./src` folder. 

The compile check confirmed that the template is passing with latest version of typst, so it's not there you should dig into. 

My largest doubt is that you might not include the `--font-path` flag when compiling, which also explains why the Roboto font is not working.

**Comment by PabloRuizCuevas** [comment]
Thanks not is working, I thought the --font was not realted with the icons so didn´t include the path, my fault. We can close this issue, and thanks for the template looks fantastic :))

**Comment by mintyfrankie** [comment]
With pleasure!
