### ISSUE TITLE
update project section to include github link

### ISSUE THREAD

**Issue by Mehboob-Khan** [mintyfrankie/brilliant-CV#12]
![image](https://github.com/mintyfrankie/brilliant-CV/assets/84440096/61616f65-3e79-4fd4-880f-7429179baee7)

please can we have something like this for projects so when we click the link we are redirected to source code

**Comment by mintyfrankie** [comment]
This one looks cool! Can you share the link for this template please?

Per se I think it's doable.

**Comment by Mehboob-Khan** [comment]
https://github.com/tensorush/cv

**Comment by mintyfrankie** [comment]
Thanks! I will see what I can do.

**Comment by mintyfrankie** [comment]
Just took a look and actually this doesn't require template support update -- all you need to do is to add a `link` function in your project section.

If you fancy a GitHub icon, you can import the fontawesome package in your specific file and call it directly.

Example - in your `projects.typ`:

Import the package at the top of the file
```
#import "@preview/fontawesome:0.1.0": *
```

And make your entry
```
#cvEntry(
  title: [Volunteer Data Analyst],
  society: [#fa-github() #link("https://github.com/mintyfrankie/brilliant-CV")[mintyfrankie/brilliant-CV]],
  date: [2019 - Present],
  location: [New York, NY],
  description:...
  )
)
```

Output: 
![CleanShot 2023-09-19 at 09 17 15](https://github.com/mintyfrankie/brilliant-CV/assets/77310871/4c50a2cf-c6f8-4876-b98c-389a23b8dc2f)

I am closing this issue as it doesn't require further update. Feel free to submit another issue if you have more ideas.
