### ISSUE TITLE
live version Switching

### ISSUE THREAD

**Issue by HernandoR** [mintyfrankie/brilliant-CV#13]
**Is your feature request related to a problem? Please describe.**
Mostly, if I updated my CV, I would like to update all languages and compile them all.

Switch behavior by source editing seems unnatural

**Describe the solution you'd like**
Pass the desired languages by cmdline args, or change the varLanguage into a list

**Describe alternatives you've considered**
Furthermore. It feels more reasonable to nast the language entry in the file i.e. like the `metadata.typ`

-----

I realize that it is a language limitation that each compile can only output one PDF. and also if the cmdline can pass args to the template

**Comment by mintyfrankie** [comment]
A very interesting proposal, I see your point here.

I will be happy to implement this if Typst expands this functionality: https://github.com/typst/typst/issues/295

In the meanwhile, you might want to write a simple bash script that change the variable in the `metadata.typ` by commands like `sed` and compile the file, such that you could execute the script once and get the PDF for all versions.

**Comment by HernandoR** [comment]
I made a minor change to support this feature. Please have a look at [my repo](https://github.com/HernandoR/lz-brilliant-cv) for the use of multi-version support, and [my repo of template](https://github.com/HernandoR/brilliant-CV-Submodule) for information.

Let me know if you'd like to pull my changes, I'll raise a PR

**Comment by mintyfrankie** [comment]
I took a look but I don't quite understand your repo -- so it is that you added a `varVersion` and it's all?

You can submit a PR if you want though. It would be clearer to review altogether.

**Comment by mintyfrankie** [comment]
Follow up discussion will be in https://github.com/mintyfrankie/brilliant-CV-Submodule/pull/9
