### ISSUE TITLE
Is the CV ats Parseable

### ISSUE THREAD

**Issue by Mehboob-Khan** [mintyfrankie/brilliant-CV#14]

**Comment by mintyfrankie** [comment]
Could you elaborate more on the issue?

**Comment by Mehboob-Khan** [comment]
The idea behind making the CV ATS parseable is to ensure that it can be easily read and understood by Applicant Tracking Systems (ATS) that many companies use for their hiring process. This optimization allows candidates’ information to be efficiently processed, improving their chances of being considered for positions. It’s an important consideration for job seekers and can enhance the overall effectiveness of the application process.

It might be ATS might be not....

**Comment by mintyfrankie** [comment]
Well I haven't tested it myself, but there is nothing I can do if that wasn't the case. All beyond templating is at Typst's hand.

I've done however once my CV written in this template by an ATS-like engine and it didn't has any issue.
