### ISSUE TITLE
Ability to omit `headerQuoteInternational`

### ISSUE THREAD

**Issue by davidedellagiustina** [mintyfrankie/brilliant-CV#16]
**Is your feature request related to a problem? Please describe.**
If `headerQuoteInternational` is left empty, the space that it takes is left blank instead of being occupied by the content that follows.

**Describe the solution you'd like**
The vertical spacing should adjust automatically if a header quote is not provided (or empty).

**Comment by mintyfrankie** [comment]
Hi @davidedellagiustina thanks for the issue, and excuses for the late reply, I've been quite busy recently.

Just looked into the issue you've mentioned, and to me it seems to be more of an issue related to how header section is constructed. With a `headerPhoto` of 3.6cm in height, one cannot omit actually the space for `headerQuote`, even though it is empty.

And in my personal opinion, having consistency on the top of the page can also be great, if one is to change/delete the `headerQuote` frequently.

Closing this issue as it won't be treated in near future, but feel free to submit a PR if you want to suggest a better implementation.

**Comment by davidedellagiustina** [comment]
Thanks for your answer @mintyfrankie!

In the end, I ended up tweaking your template quite a bit here and there, and made my personal version according to my personal needs and taste.

Thank you anyway!

**Comment by mintyfrankie** [comment]
> Thanks for your answer @mintyfrankie!
> 
> In the end, I ended up tweaking your template quite a bit here and there, and made my personal version according to my personal needs and taste.
> 
> Thank you anyway!

Good to know! 😄
