### ISSUE TITLE
Grade in education section?

### ISSUE THREAD

**Issue by Mehboob-Khan** [mintyfrankie/brilliant-CV#18]
bro i would  appreciate if you could add a grade in bold without adding a bullet point into it, in education section that would be lit

**Comment by mintyfrankie** [comment]
Hi @Mehboob-Khan, what I will do it's simply to insert a soft enter or a `hBar` and then put grade after either your degree title or anything else. This is simple formatting without the need to template.

Or you might have a specific example to showcase your idea?
