### ISSUE TITLE
Feature request: improve usage documentation for `cvSection`

### ISSUE THREAD

**Issue by avi-cenna** [mintyfrankie/brilliant-CV#19]
I would like to be able to produce a resume without highlighting the first 3 letters of the section. After looking through the code, it seems like it's possible to do this by passing in a false value into the `cvSection` function (included below for reference). It would be nice to have some documentation which clarifies some of the ways this template can be customized.

If this seems like a reasonable request, I would probably be able to submit a pull request for this.

```typst
#let cvSection(title, highlighted: true, letters: 3) = {
  let highlightText = title.slice(0, letters)
  let normalText = title.slice(letters)

  v(beforeSectionSkip)
  if nonLatinOverwrite {
    sectionTitleStyle(title, color: accentColor)
  } else {
    if highlighted {
      sectionTitleStyle(highlightText, color: accentColor)
      sectionTitleStyle(normalText, color: black)
    } else {
      sectionTitleStyle(title, color: black)
    }
  }
  h(2pt)
  box(width: 1fr, line(stroke: 0.9pt, length: 100%))
}

```

**Comment by mintyfrankie** [comment]
Hi @avi-cenna thanks for this advice! It's absolutely legitimate and valuable. 

Indeed I am also thinking about making a small documentation for the project, perhaps using the ![Tidy](https://github.com/Mc-Zen/tidy) package to generate a small PDF included in the repository. 

Are you interested in working together for this one?

**Comment by avi-cenna** [comment]
Hello @mintyfrankie , yeah that sounds good to me! I didn't know about the Tidy package, but I think that would be helpful by converting documentation comments into readable API documentation.

**Comment by mintyfrankie** [comment]
Hi @avi-cenna, I plan now to cover this issue within the new `v2` version, that will be complied also to the Typst package standards. A better documentation is on the roadmap. Please stay in touch!
