### ISSUE TITLE
how to make this resume in 2 column format?

### ISSUE THREAD

**Issue by goyalyashpal** [mintyfrankie/brilliant-CV#22]
**Is your feature request related to a problem? Please describe.**
* the current format renders the result only in one column format. 
* for freshers, generally the details are bulleted and very rarely in a paragraph format, 
* so, a huge amount of space goes unutilized and wasted; and the cv stretches to even 2 pages which is even worse

**Describe the solution you'd like**
ideally, some predefined way to specify 2 column format.

but even some documentation or vectors on what changes would be required to make this in 2 format would be appreciated too 😃 

**Describe alternatives you've considered**
n/a

**Additional context**
this concerns the cv, not the cover letter.

**Comment by mintyfrankie** [comment]
Hi @goyalyashpal, thanks for proposing this point.

I have no intention supporting two-column layout for the time being, this is an opinionated choice. 

However feel free to propose a PR or fork this repository to implement yourself if you find it imperative. Happy to review it to see how it goes.
