### ISSUE TITLE
Custom field in headerInfo in metadata.toml might not work

### ISSUE THREAD

**Issue by mintyfrankie** [mintyfrankie/brilliant-CV#32]

**Comment by ericthomasca** [comment]
Can confirm. Will looking into possible fixes.

**Comment by mintyfrankie** [comment]
Hi @ericthomasca thanks for the confirmation! I've created a new PR to address this issue, progress are made but yet it does not resolve the icon issue due to the scoping of `eval` function. Don't hesitate if you would like to contribute!

**Comment by ericthomasca** [comment]
I'm new to typst, I'll do what I can.
