### ISSUE TITLE
Need documentation of upgrade process

### ISSUE THREAD

**Issue by ericthomasca** [mintyfrankie/brilliant-CV#47]
What I assumed the upgrade process is was to just change all instances of the version number with the latest version number, like so:

![Screenshot_20240729_110843](https://github.com/user-attachments/assets/cf5b0419-d3ee-49da-a50d-bc4e218b885a)

Is it possible to use a `latest` tag? Or is the "find and replace" method the only way?

Either way, there should be something in the README.

**Comment by mintyfrankie** [comment]
Hi @ericthomasca I think for the time being is a simple "find and replace". It should be quite simple to do in an IDE.

I don't think there is a `latest` tag yet, perhaps to come once we go out of `@preview` scope maybe. Will look into it tonight when I get some time. 

Btw, it would be great to have your opinion on #46; how do you think of it?

**Comment by mintyfrankie** [comment]
Btw I am not sure if Typst has already rolled out `v2.0.1` on their CDN; it seems to have a bit of delay. Keep me posted if there is a problem.

**Comment by ericthomasca** [comment]
I noticed it's still 2.0.0 listed on the typst site, but I changed the version number and it worked.

**Comment by mintyfrankie** [comment]
A short section was added to the README file to document this process. This should be enough I think.

**Comment by ericthomasca** [comment]
Looks good to me
