### ISSUE TITLE
An unwanted comma in name title of CV

### ISSUE THREAD

**Issue by Ye-Jinhong** [mintyfrankie/brilliant-CV#52]
**Describe the bug**
An additional "," is shown unexpectedly on title

**To Reproduce**
1. `typst init @preview/brilliant-cv:2.0.1`
2. `cd brilliant-cv`
3. change the language to "zh" in metadata.toml
4. `typst -c cv.typ`
5. See error in cv.pdf

**Expected behavior**
There is only Chinese name on title.

**Screenshots**
![image](https://github.com/user-attachments/assets/8a81c2ee-2d8f-4ac0-a121-bec00253d452)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Typst V0.11.1
 - Version 2.0.1

**Comment by mintyfrankie** [comment]
Hi @Ye-Jinhong thanks for spotting this! I confirm this is a replicable bug.

I will fix this ASAP, but please be noted that it will be shipped with `v2.0.2`, which can take some more time for Typst to merge these changes.

**Comment by mintyfrankie** [comment]
Update: this seems to only appear when target language is non-latin.
