### ISSUE TITLE
Font Awesome icons not working

### ISSUE THREAD

**Issue by polarr** [mintyfrankie/brilliant-CV#57]
**Describe the bug**

FA icons not working, everything else seems to be working fine.

**To Reproduce**
1. Go to Typst online editor
2. Use this template
3. See error

**Expected behavior**

Icons work

**Screenshots**
![image](https://github.com/user-attachments/assets/28ec36bf-37f4-4374-b7eb-d38190a76844)

**Desktop (please complete the following information):**
 - Browser Firefox

**Comment by mintyfrankie** [comment]
Hi @polarr,

can you please confirm if this step is well respected, as per to the documentation:

> NOTE: For online editor, Source Sans Pro are already included; however you will still have to manually upload the .otf or .ttf files of Fontawesome and Roboto to your project, by creating a folder fonts and put all the otf files there. See https://github.com/typst/webapp-issues/issues/401

Also, a screenshot of your Typst app workspace file structure can help identify the issue.

**Comment by polarr** [comment]
Sorry, I somehow missed that part. It works fine.

Thanks for the help!

**Comment by mintyfrankie** [comment]
No worries, great to hear!

**Comment by SimonIT** [comment]
Is this note anywhere to be found? I don't see it anywhere!
