### ISSUE TITLE
Changing or adding icons in the headerInfo doesn't work as expected

### ISSUE THREAD

**Issue by munzirtaha** [mintyfrankie/brilliant-CV#59]
Icons choices differ from person to person. Having a reasonable default is preferable for most people, but there should be a simple way to alter it if desired. I want to change the default telephone headset icon to a mobile icon '\u{1F4F1}'. It seems it's hardcoded and only use FontAwesome font. So, I just removed it and tried to add it using

`awesomeIcon = "📱"` and `awesomeIcon = "\u{1F4F1}"`

But both options didn't work.

**Comment by mintyfrankie** [comment]
Just took a look at it, it is going to be very hacky or complicated as long as Typst doesn't propose a better path handling mechanism. Also, toml file is really not handled for this kind of customized usage in Typst.

I suggest to close the issue for the time being, for the sake of keeping the template simple. Don't hesitate to fork, modify and use this template locally.
