### ISSUE TITLE
Can no longer emphasize a word

### ISSUE THREAD

**Issue by munzirtaha** [mintyfrankie/brilliant-CV#60]
As far as I recall, in the previous version, typst's **asterisk/star** syntax to emphasis a word was working e.g. In `[*Thesis:*....]`, but this no longer works.

**Comment by mintyfrankie** [comment]
Hello again @munzirtaha! This is not normal, could you please elaborate more on the context: in which function, with what parameter, etc? Some screenshots might really help identify the issue.

**Comment by munzirtaha** [comment]
I am sorry, this seems to be a problem related to typst handling of fonts variants and changing the font solved it. It has nothing to do with your code. Thanks for your consideration.
