### ISSUE TITLE
Bottom margin is too small

### ISSUE THREAD

**Issue by oyvindskaaden** [mintyfrankie/brilliant-CV#69]
**Describe the bug**
The bottom margin is too small. Content interferes with the footer.

**To Reproduce**
1. Make enough entries to fill more than one page.

**Expected behavior**
I would expect the content to do a pagebreak before reaching the footer.

**Screenshots**
<img width="395" alt="image" src="https://github.com/user-attachments/assets/3fa624a0-a358-4d9e-9bb2-f54a1a1d8455">

**Desktop (please complete the following information):**
 - OS: MacOS 14
 - Browser Firefox
 - Version v130

**Typst Web Editor**
Typst version: 0.11.1

**Additional context**
Could be added into the `metadata.toml`

**Comment by oyvindskaaden** [comment]
I have found that changing the margins to 
```rust
margin: (left: 1.4cm, right: 1.4cm, top: 1.0cm, bottom: 1.0cm)
```
the pagebreaking works correctly.

**Comment by mintyfrankie** [comment]
Hi @oyvindskaaden thanks for reporting this!

Recent version upgrade of `v2.0.3` introduced a new way to handle footer, it could be that change interfering with the margin. What is your package version? If it's `v2.0.3`, could you please roll back to `v2.0.2` and tell me if the problem persists?

**Comment by oyvindskaaden** [comment]
Hi!

When rolling back to `v2.0.2` the footer just dissapairs:
<img width="395" alt="image" src="https://github.com/user-attachments/assets/20b99781-68e6-482c-8c76-146ea36b8291">

It is the same behaviour as `v2.0.0` through `v2.0.2`.

**Comment by mintyfrankie** [comment]
That's weird, are you having a multi-page CV?

I will look into this more in details, thanks for the extra information!

**Comment by yslflow** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by mintyfrankie** [comment]
Hi thanks for the patience! Finally got the time to sit down and patch this one. I've adopted your values, even though it might eats out two lines but the overall aesthetic seems to be better.

Will package this one for the next version update at Typst repository. Thanks!
