### ISSUE TITLE
Customize Font Style for different part of entry

### ISSUE THREAD

**Issue by taooceros** [mintyfrankie/brilliant-CV#70]
Is it possible to customize the font size and font family for different part in the `cvEntry`? For example like in the `cvEntry`, we already have different spec for Title, Society, date, location, etc. It might be better to allow customization of their style in the metadata. This should not be hard, but mostly just replacing those constant with a variable in the metadata.

Certainly it is always possible to override the default by manually writing the style, but it would be nice if this can be done with the template.

**Comment by mintyfrankie** [comment]
Hi @taooceros! Please see #58.

I should probably add in the description how one can modify and clone locally this template and make their changements, but yes, unfortunately this is not a feature on the horizon for me.

**Comment by taooceros** [comment]
Thanks for replying. I understand your decision about not leaving user too much space for customization. However, I feel like cloning the library and changing the hardcoded font style is probably not an elegant solution. It will make pulling the upstream change pretty hard (due to the potential of large number of conflict). I feel like this is likely to divert the community, which might not be a good thing.

On the other hand, how about making the font size customizable via the `show set` rule? I am not sure how typst std library like header is implemented, but there should be ways to make specific section selectable from the `show set` rule?

**Comment by taooceros** [comment]
well I guess this is not supported...
