### ISSUE TITLE
2.0.3 Breaks cover letter headers and footers

### ISSUE THREAD

**Issue by Roukoswarf** [mintyfrankie/brilliant-CV#71]
**Describe the bug**
Between 2.0.2 and 2.0.3 the change in footer code also moved the letter header into the footer, causing the footer to flow off the end of the page, instead of being in the header.

**To Reproduce**
1. Compile the example letter.typ
2. View missing header, and the beginnings of the My Name at the bottom of the page.

**Expected behavior**
The original result which is produced by 2.0.2

**Desktop:**
 - OS: Linux
 - Typst Version: 0.12
 - Brilliant-CV Version:  2.0.3

**Comment by mintyfrankie** [comment]
Thanks for submitting this bug @Roukoswarf! Yeah indeed it seems to me that there is an omission.

Will fix it ASAP.

**Comment by yslflow** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by mintyfrankie** [comment]
Hi thanks for the patience! Finally got the time to sit down and patch this one. I've adopted your values, even though it might eats out two lines but the overall aesthetic seems to be better.

Will package this one for the next version update at Typst repository. Thanks!

**Comment by mintyfrankie** [comment]
Sorry for the oversight, I guessed I just shot at my foot 😅

I just patched the fix and will also package this one in the next update in Typst repository.

Thanks!
